// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmdjeqchbgryvakljpnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZGplcWNoYmdyeXZha2xqcG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDMyMTgsImV4cCI6MjA2MTE3OTIxOH0.uQ6zaVwAGRZigjrLNzHTlMqQ7Sp2O9cidAXsS7HgVdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);